# Generated by Django 5.0.7 on 2024-08-04 23:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('telegram_id', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseGraphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/course/graphics/')),
                ('video_file', models.FileField(upload_to='videos/course/graphics/')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=5000)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('level', models.CharField(max_length=40)),
                ('start_date', models.DateField()),
                ('time_limit', models.TimeField(default=datetime.datetime(2024, 8, 4, 15, 26, 52, 13177))),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/course/front/')),
                ('video_file', models.FileField(upload_to='videos/course/front/')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=5000)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('level', models.CharField(max_length=40)),
                ('start_date', models.DateField()),
                ('time_limit', models.TimeField(default=datetime.datetime(2024, 8, 4, 15, 26, 52, 12173))),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='CourseBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/course/back/')),
                ('video_file', models.FileField(upload_to='videos/course/back')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=5000)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('level', models.CharField(max_length=40)),
                ('start_date', models.DateField()),
                ('time_limit', models.TimeField(default=datetime.datetime(2024, 8, 4, 15, 26, 52, 12173))),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.teachers')),
            ],
        ),
    ]
